title: Lynn Blog
description: Business grad diving into data â€” building skills, asking questions, making sense of the noise. ğŸµ
author: Hyelin yu
theme: theme: jekyll-theme-minimal

# ì–¸ì–´ ì„¤ì •ğŸµ
lang: ko

# ë¸”ë¡œê·¸ ì£¼ì†Œ ì„¤ì •
baseurl: "" # github.io ë„ë©”ì¸ ì“°ëŠ” ê²½ìš°ëŠ” ë¹„ì›Œë‘ 
url: "https://hyelinyu.github.io" # ì—¬ê¸°ì— ë³¸ì¸ ì£¼ì†Œ ì…ë ¥
